keys:
    - &host_hostname age1kf5tknpnhsxk7g9eket2vra58qft9ndyy4ua0k4xc9d4p7qh4d7s4wggcw
creation_rules:
    - path_regex: secrets.yaml$
      key_groups:
        - age:
            - *host_hostname
